---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: 'Test GitHub Action 🧪'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  # Cannot be tested on pull request; secrets not available
  push:
    branches: ['main']

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

permissions: {}

env:
  tag: '0.0.1-dev0'

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: 'Test local GitHub Action'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: 'Checkout repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Perform setup prior to running test(s)
      - name: 'Checkout sample project repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "lfreleng-actions/test-python-project"
          path: 'test-python-project'

      - name: 'Build Python project'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/python-build-action@f3b78ac710af9dca46c5c4562f53ac3660f2ea59 # v0.1.7
        with:
          tag: "${{ env.tag }}"
          path_prefix: 'test-python-project'

      - name: "Running local action: ${{ github.repository }}"
        uses: ./
        with:
          path_prefix: 'test-python-project'
          tag: "${{ env.tag }}"
          no_checkout: true
          op_service_account_token: "${{ secrets.op_service_account_token }}"
          one_password_item: "${{ vars.one_password_item }}"
          pypi_credential: "${{ secrets.pypi_credential }}"
          publish_disable: true
